on:
  push:
    branches:
      - master
  pull_request:

name: Checks

jobs:
  check:
    name: sanity checks
    runs-on: ubuntu20.04-4cores-16GB
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: cargo fmt
        run: cargo fmt --all -- --check
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: cargo build
        run: cargo build --locked --bin afn
